import { writeBlockFile } from '../header';
import type { Library, Manifest, Piece } from '../library';
import {
  SLOT_IDS,
  type BlockModel,
  type ConditionExpr,
  type PieceRef,
  type SlotId,
  type Statement,
} from '../model';
import { createLabelAllocator, render, TemplateError, type Value } from '../template';

export interface GenerateOptions {
  /** Written into the human header ("Generated by BlockCreator <version>"). */
  toolVersion?: string;
}

/** Where a generated line comes from: a Slot and the path of a statement in its tree. */
export interface LineOrigin {
  slot: SlotId;
  /** JSON-pointer-like path into the Slot's statements, e.g. `/0/branches/1/condition`. */
  path: string;
}

export interface GenerateResult {
  text: string;
  /** 1-based line number → origin, for every line produced by a Slot's statements. */
  lineMap: ReadonlyMap<number, LineOrigin>;
}

export class GenerateError extends Error {
  constructor(
    message: string,
    readonly origin: LineOrigin,
  ) {
    super(`${origin.slot} ${origin.path}: ${message}`);
    this.name = 'GenerateError';
  }
}

/** GPS offsets in jump-table order (`db $42`: 10 offsets). */
const OFFSETS = [
  'MarioBelow',
  'MarioAbove',
  'MarioSide',
  'SpriteV',
  'SpriteH',
  'MarioCape',
  'MarioFireball',
  'TopCorner',
  'BodyInside',
  'HeadInside',
] as const;
type Offset = (typeof OFFSETS)[number];

/** Offsets per jump-table line, as in GPS's template.asm. */
const JUMP_TABLE_ROWS = [3, 4, 3];

const SLOT_OFFSETS: Record<SlotId, Offset[]> = {
  marioTop: ['MarioAbove'],
  marioBottom: ['MarioBelow'],
  marioInside: ['BodyInside', 'HeadInside'],
};

/**
 * Generates the GPS `.asm` for a Block: machine header (ADR 1), human header, jump table, one
 * section per filled Slot, a shared `RTL` for empty offsets, and the Lunar Magic tooltip.
 * Deterministic: the same model and Library give byte-identical text.
 */
export function generate(
  model: BlockModel,
  library: Library,
  options: GenerateOptions = {},
): GenerateResult {
  const code = new CodeWriter();
  const emitter = new Emitter(library, code);
  const filled = SLOT_IDS.filter((slot) => (model.slots[slot] ?? []).length > 0).sort(
    (a, b) => OFFSETS.indexOf(SLOT_OFFSETS[a][0]!) - OFFSETS.indexOf(SLOT_OFFSETS[b][0]!),
  );
  for (const slot of filled) {
    for (const offset of SLOT_OFFSETS[slot]) code.label(offset);
    emitter.statements(model.slots[slot]!, { slot, path: '' });
    code.line('RTL');
    code.blank();
  }
  const used = new Set(filled.flatMap((slot) => SLOT_OFFSETS[slot]));
  for (const offset of OFFSETS.filter((o) => !used.has(o))) code.label(offset);
  code.line('RTL');

  const beforeCode = [
    ...humanHeader(model, emitter.usedPieces(), options.toolVersion ?? 'dev'),
    '',
    'db $42',
    ...jumpTable(),
    '',
  ];
  const body = [...beforeCode, ...code.lines, ...tooltip(model.properties.description)];
  const bodyText = body.map((line) => line + '\n').join('');
  const text = writeBlockFile(model, bodyText);

  const machineHeaderLines = lineCount(text) - lineCount(bodyText);
  const firstCodeLine = machineHeaderLines + beforeCode.length + 1;
  const lineMap = new Map<number, LineOrigin>();
  code.origins.forEach((origin, i) => {
    if (origin) lineMap.set(firstCodeLine + i, origin);
  });
  return { text, lineMap };
}

function lineCount(text: string): number {
  return text.split('\n').length - 1;
}

function jumpTable(): string[] {
  let next = 0;
  return JUMP_TABLE_ROWS.map((size) =>
    OFFSETS.slice(next, (next += size))
      .map((offset) => `JMP ${offset}`)
      .join(' : '),
  );
}

function humanHeader(model: BlockModel, pieces: Piece[], toolVersion: string): string[] {
  const { name, author, description, defaultActAs } = model.properties;
  const paragraphs: string[][] = [
    [
      oneLine(name),
      `Generated by BlockCreator ${toolVersion}. Edit this Block in BlockCreator; hand edits are overwritten.`,
      ...(author.trim() ? [`Author: ${oneLine(author)}`] : []),
      `Insert with act as ${defaultActAs.toString(16).toUpperCase().padStart(3, '0')}.`,
    ],
  ];
  if (description.trim()) paragraphs.push(description.trim().split(/\r?\n/));
  const credited = pieces.filter((piece) => piece.manifest.credits);
  if (credited.length > 0) {
    paragraphs.push(
      credited.map((p) => `Credits (${oneLine(p.manifest.name)}): ${oneLine(p.manifest.credits!)}`),
    );
  }
  const routines = [...new Set(pieces.flatMap((piece) => piece.manifest.routines))].sort();
  if (routines.length > 0) paragraphs.push([`Needs GPS routines: ${routines.join(', ')}`]);
  return [
    ';',
    ...paragraphs.flatMap((lines) => [...lines.map((line) => `; ${line}`.trimEnd()), ';']),
  ];
}

/** Collapses line breaks so free text cannot escape its comment line. */
function oneLine(text: string): string {
  return text.trim().replace(/\s*\r?\n\s*/g, ' ');
}

/** `print` shows the description as the Block's tooltip in Lunar Magic. */
function tooltip(description: string): string[] {
  const text = description.trim().replace(/\s+/g, ' ').replace(/"/g, "'");
  return text ? ['', `print "${text}"`] : [];
}

/** Collects code lines with their origin; indents instructions, keeps labels in column 0. */
class CodeWriter {
  readonly lines: string[] = [];
  readonly origins: (LineOrigin | undefined)[] = [];

  label(name: string, origin?: LineOrigin): void {
    this.push(`${name}:`, origin);
  }

  line(instruction: string, origin?: LineOrigin): void {
    this.push(`\t${instruction}`, origin);
  }

  blank(): void {
    this.push('', undefined);
  }

  /** Adds a Piece's rendered template line by line. */
  pieceCode(rendered: string, origin: LineOrigin): void {
    const lines = rendered.replace(/\r\n/g, '\n').replace(/\n$/, '').split('\n');
    for (const raw of lines) {
      const line = raw.trim();
      if (line === '') this.push('', origin);
      else if (/^[^\s;]+:(\s*;.*)?$/.test(line)) this.push(line, origin);
      else this.push(`\t${line}`, origin);
    }
  }

  private push(text: string, origin: LineOrigin | undefined): void {
    this.lines.push(text);
    this.origins.push(origin);
  }
}

const ARTICLE: Record<Manifest['kind'], string> = {
  action: 'an Action',
  condition: 'a Condition',
};

/** Walks a Slot's statements and writes their code. One label allocator per Block. */
class Emitter {
  private readonly labels = createLabelAllocator();
  private readonly used = new Map<string, Piece>();

  constructor(
    private readonly library: Library,
    private readonly out: CodeWriter,
  ) {}

  /** Pieces used so far, by id in code-unit order (locale-independent, so output is stable). */
  usedPieces(): Piece[] {
    return [...this.used.keys()].sort().map((id) => this.used.get(id)!);
  }

  statements(statements: Statement[], parent: LineOrigin): void {
    statements.forEach((statement, i) => this.statement(statement, at(parent, i)));
  }

  private statement(statement: Statement, origin: LineOrigin): void {
    if (statement.type === 'action') {
      this.out.pieceCode(this.renderPiece(statement.piece, 'action', origin), origin);
      return;
    }
    const label = this.labels.instance();
    const { branches } = statement;
    branches.forEach((branch, i) => {
      const last = i === branches.length - 1;
      const falseTarget = !last ? `branch${i + 2}` : statement.else ? 'else' : 'end';
      const branchOrigin = at(origin, 'branches', i);
      if (i > 0) this.out.label(label(`branch${i + 1}`), origin);
      this.condition(branch.condition, at(branchOrigin, 'condition'), label(falseTarget));
      this.statements(branch.body, at(branchOrigin, 'body'));
      if (!last || statement.else) this.out.line(`BRA ${label('end')}`, origin);
    });
    if (statement.else) {
      this.out.label(label('else'), origin);
      this.statements(statement.else, at(origin, 'else'));
    }
    this.out.label(label('end'), origin);
  }

  private condition(expr: ConditionExpr, origin: LineOrigin, falseLabel: string): void {
    this.out.pieceCode(this.renderPiece(expr.piece, 'condition', origin, falseLabel), origin);
  }

  private renderPiece(
    ref: PieceRef,
    kind: Manifest['kind'],
    origin: LineOrigin,
    falseLabel?: string,
  ): string {
    const piece = this.library.pieces.get(ref.id);
    if (!piece) throw new GenerateError(`Piece '${ref.id}' is not in the Library`, origin);
    if (piece.manifest.kind !== kind) {
      throw new GenerateError(
        `Piece '${ref.id}' is ${ARTICLE[piece.manifest.kind]}, not ${ARTICLE[kind]}`,
        origin,
      );
    }
    this.used.set(ref.id, piece);
    const params: Record<string, Value> = {
      ...Object.fromEntries(piece.manifest.params.map((p) => [p.name, p.default])),
      ...ref.params,
    };
    try {
      return render(piece.template, {
        params,
        label: this.labels.instance(),
        ...(falseLabel !== undefined && { falseLabel }),
      });
    } catch (error) {
      if (error instanceof TemplateError) {
        throw new GenerateError(`Piece '${ref.id}': ${error.message}`, origin);
      }
      throw error;
    }
  }
}

/** The origin of a child in the statement tree, e.g. `at({…, path: '/0'}, 'branches', 1)`. */
function at(origin: LineOrigin, ...steps: (string | number)[]): LineOrigin {
  return { slot: origin.slot, path: `${origin.path}/${steps.join('/')}` };
}
