import { writeBlockFile } from '../header';
import type { Library, Manifest, Piece, Register } from '../library';
import {
  effectiveSlot,
  effectiveSlotStatements,
  fitsSlot,
  SLOT_KIND_NAMES,
  slotKind,
  type BlockModel,
  type ConditionExpr,
  type PieceRef,
  type SlotId,
  type Statement,
} from '../model';
import { createLabelAllocator, render, TemplateError, type Value } from '../template';
import { widenBranches } from './branches';
import { JUMP_TABLE_ROWS, planSections, type Offset, type Section, type Split } from './sections';

export interface GenerateOptions {
  /** Written into the human header ("Generated by BlockCreator <version>"). */
  toolVersion?: string;
}

/** Where a generated line comes from: a Slot and the path of a statement in its tree. */
export interface LineOrigin {
  slot: SlotId;
  /** JSON-pointer-like path into the Slot's statements, e.g. `/0/branches/1/condition`. */
  path: string;
}

export interface GenerateResult {
  text: string;
  /** 1-based line number → origin, for every line produced by a Slot's statements. */
  lineMap: ReadonlyMap<number, LineOrigin>;
  /** The tool routines (`bc_*`) the Block calls, sorted: they must be in the GPS project. */
  routines: readonly string[];
}

export class GenerateError extends Error {
  constructor(
    message: string,
    readonly origin: LineOrigin,
  ) {
    super(`${origin.slot} ${origin.path}: ${message}`);
    this.name = 'GenerateError';
  }
}

/**
 * Generates the GPS `.asm` for a Block: machine header (ADR 1), human header, jump table, one
 * section per filled Slot (or pair of split Slots), a shared `RTL` for empty offsets, and the
 * Lunar Magic tooltip. Deterministic: the same model and Library give byte-identical text.
 */
export function generate(
  model: BlockModel,
  library: Library,
  options: GenerateOptions = {},
): GenerateResult {
  const code = new CodeWriter();
  const labels = createLabelAllocator();
  const emitter = new Emitter(library, code, labels);
  const plan = planSections(model);

  // Count how many times each effective slot is executed across all sections
  const slotReferences = new Map<SlotId, number>();
  for (const section of plan.sections) {
    if (section.kind === 'slot') {
      const eff = effectiveSlot(model, section.slot);
      if (effectiveSlotStatements(model, eff).length > 0) {
        slotReferences.set(eff, (slotReferences.get(eff) ?? 0) + 1);
      }
    } else {
      const effFirst = effectiveSlot(model, section.split.first);
      if (effectiveSlotStatements(model, effFirst).length > 0) {
        slotReferences.set(effFirst, (slotReferences.get(effFirst) ?? 0) + 1);
      }
      const effSecond = effectiveSlot(model, section.split.second);
      if (effectiveSlotStatements(model, effSecond).length > 0) {
        slotReferences.set(effSecond, (slotReferences.get(effSecond) ?? 0) + 1);
      }
    }
  }

  // Create shared labels for slots referenced > 1 times
  const sharedLabels = new Map<SlotId, string>();
  for (const [slot, count] of slotReferences.entries()) {
    if (count > 1) {
      sharedLabels.set(slot, labels.instance()('shared_' + slot));
    }
  }

  // Choose home section for each shared slot:
  // Prefer section.kind === 'slot' if one exists, otherwise the first section that references it.
  const effHome = new Map<SlotId, Section>();
  for (const [eff] of sharedLabels) {
    const slotSec = plan.sections.find(
      (s) => s.kind === 'slot' && effectiveSlot(model, s.slot) === eff,
    );
    if (slotSec) {
      effHome.set(eff, slotSec);
    } else {
      const splitSec = plan.sections.find(
        (s) =>
          s.kind === 'split' &&
          (effectiveSlot(model, s.split.first) === eff ||
            effectiveSlot(model, s.split.second) === eff),
      );
      if (splitSec) effHome.set(eff, splitSec);
    }
  }

  for (const section of plan.sections) {
    for (const offset of section.offsets) code.label(offset);
    if (section.kind === 'slot') {
      if (section.offsets.some((o) => o === 'SpriteV' || o === 'SpriteH')) {
        code.line('%sprite_block_position()');
      }
      const eff = effectiveSlot(model, section.slot);
      const sharedLabel = sharedLabels.get(eff);
      if (sharedLabel) {
        if (effHome.get(eff) === section) {
          code.label(sharedLabel);
          emitter.statements(effectiveSlotStatements(model, eff), { slot: eff, path: '' });
        } else {
          code.line(`BRA ${sharedLabel}`);
        }
      } else {
        emitter.statements(effectiveSlotStatements(model, eff), { slot: eff, path: '' });
      }
    } else {
      emitter.split(section.split, model, sharedLabels, effHome, section);
    }
    code.line('RTL');
    code.blank();
  }
  for (const offset of plan.empty) code.label(offset);
  code.line('RTL');
  const widened = widenBranches(code.lines, code.origins, () => labels.instance());

  const usedPieces = emitter.usedPieces();
  const beforeCode = [
    ...humanHeader(model, usedPieces, options.toolVersion ?? 'dev'),
    '',
    plan.wallRun ? 'db $37' : 'db $42',
    ...jumpTable(plan.offsets),
    '',
  ];
  const body = [...beforeCode, ...widened.lines, ...tooltip(model.properties.description)];
  const bodyText = body.map((line) => line + '\n').join('');
  const text = writeBlockFile(model, bodyText);

  const machineHeaderLines = lineCount(text) - lineCount(bodyText);
  const firstCodeLine = machineHeaderLines + beforeCode.length + 1;
  const lineMap = new Map<number, LineOrigin>();
  widened.origins.forEach((origin, i) => {
    if (origin) lineMap.set(firstCodeLine + i, origin);
  });
  return { text, lineMap, routines: neededRoutines(usedPieces) };
}

function lineCount(text: string): number {
  return text.split('\n').length - 1;
}

function jumpTable(offsets: readonly Offset[]): string[] {
  let next = 0;
  return JUMP_TABLE_ROWS.map((size) => offsets.slice(next, (next += size)))
    .filter((row) => row.length > 0)
    .map((row) => row.map((offset) => `JMP ${offset}`).join(' : '));
}

/** The tool routines the Pieces call, sorted and without repeats. */
function neededRoutines(pieces: readonly Piece[]): string[] {
  return [...new Set(pieces.flatMap((piece) => piece.manifest.routines))].sort();
}

function humanHeader(model: BlockModel, pieces: Piece[], toolVersion: string): string[] {
  const { name, author, description, defaultActAs } = model.properties;
  const paragraphs: string[][] = [
    [
      oneLine(name),
      `Generated by BlockCreator ${toolVersion}. Edit this Block in BlockCreator; hand edits are overwritten.`,
      ...(author.trim() ? [`Author: ${oneLine(author)}`] : []),
      `Insert with act as ${defaultActAs.toString(16).toUpperCase().padStart(3, '0')}.`,
    ],
  ];
  if (description.trim()) paragraphs.push(description.trim().split(LINE_BREAKS));
  const credited = pieces.filter((piece) => piece.manifest.credits);
  if (credited.length > 0) {
    paragraphs.push(
      credited.map((p) => `Credits (${oneLine(p.manifest.name)}): ${oneLine(p.manifest.credits!)}`),
    );
  }
  const routines = neededRoutines(pieces);
  if (routines.length > 0) paragraphs.push([`Needs GPS routines: ${routines.join(', ')}`]);
  return [
    ';',
    ...paragraphs.flatMap((lines) => [...lines.map((line) => `; ${line}`.trimEnd()), ';']),
  ];
}

/** Collapses line breaks so free text cannot escape its comment line. */
function oneLine(text: string): string {
  return text.replace(LINE_BREAKS, ' ').trim();
}

/**
 * Line breaks and separators (CR, LF, U+2028, U+2029, NEL) with surrounding spaces. Built from
 * char codes so no invisible characters sit in the source.
 */
const LINE_BREAKS = new RegExp(
  `\\s*[${[0x0d, 0x0a, 0x2028, 0x2029, 0x85].map((code) => String.fromCharCode(code)).join('')}]+\\s*`,
  'g',
);

/**
 * `print` shows the description as the Block's tooltip in Lunar Magic. Asar expands `!name`
 * defines even inside strings, so `!` is escaped as `\!` (verified with Asar 1.91).
 */
function tooltip(description: string): string[] {
  const text = oneLine(description).replace(/\s+/g, ' ').replace(/"/g, "'").replace(/!/g, '\\!');
  return text ? ['', `print "${text}"`] : [];
}

/** Collects code lines with their origin; indents instructions, keeps labels in column 0. */
class CodeWriter {
  readonly lines: string[] = [];
  readonly origins: (LineOrigin | undefined)[] = [];

  label(name: string, origin?: LineOrigin): void {
    this.push(`${name}:`, origin);
  }

  line(instruction: string, origin?: LineOrigin): void {
    this.push(`\t${instruction}`, origin);
  }

  blank(): void {
    this.push('', undefined);
  }

  /** Adds a Piece's rendered template line by line. */
  pieceCode(rendered: string, origin: LineOrigin): void {
    const lines = rendered.replace(/\r\n/g, '\n').replace(/\n$/, '').split('\n');
    for (const raw of lines) {
      const line = raw.trim();
      if (line === '') this.push('', origin);
      else if (/^[^\s;]+:(\s*;.*)?$/.test(line)) this.push(line, origin);
      else this.push(`\t${line}`, origin);
    }
  }

  private push(text: string, origin: LineOrigin | undefined): void {
    this.lines.push(text);
    this.origins.push(origin);
  }
}

/** Registers the generator keeps around a Piece; A is scratch. */
type SavedRegister = Exclude<Register, 'A'>;

const ARTICLE: Record<Manifest['kind'], string> = {
  action: 'an Action',
  condition: 'a Condition',
};

/** Walks a Slot's statements and writes their code. One label allocator per Block. */
class Emitter {
  private readonly used = new Map<string, Piece>();

  constructor(
    private readonly library: Library,
    private readonly out: CodeWriter,
    /** One allocator per Block, shared with the branch rewrite so labels never collide. */
    private readonly labels: ReturnType<typeof createLabelAllocator>,
  ) {}

  /** Pieces used so far, by id in code-unit order (locale-independent, so output is stable). */
  usedPieces(): Piece[] {
    return [...this.used.keys()].sort().map((id) => this.used.get(id)!);
  }

  /** Two Slots on one offset: setup, runtime test, first Slot, then the second at its label. */
  split(
    split: Split,
    model: BlockModel,
    sharedLabels: Map<SlotId, string> = new Map(),
    effHome: Map<SlotId, Section> = new Map(),
    section?: Section,
  ): void {
    const label = this.labels.instance();
    const effFirst = effectiveSlot(model, split.first);
    const effSecond = effectiveSlot(model, split.second);
    const firstHasCode = effectiveSlotStatements(model, effFirst).length > 0;
    const secondHasCode = effectiveSlotStatements(model, effSecond).length > 0;

    const firstSharedLabel = sharedLabels.get(effFirst);
    const secondSharedLabel = sharedLabels.get(effSecond);

    const firstIsHome = Boolean(firstSharedLabel && effHome.get(effFirst) === section);
    const secondIsHome = Boolean(secondSharedLabel && effHome.get(effSecond) === section);

    for (const line of split.setup) this.out.line(line);
    this.out.line(split.test);

    // If second has a shared label elsewhere, branch directly to it!
    if (secondSharedLabel && !secondIsHome) {
      this.out.line(`${split.branch} ${secondSharedLabel}`);
      if (firstHasCode) {
        if (firstSharedLabel) {
          if (firstIsHome) {
            this.out.label(firstSharedLabel);
            this.statements(effectiveSlotStatements(model, effFirst), { slot: effFirst, path: '' });
          } else {
            this.out.line(`BRA ${firstSharedLabel}`);
          }
        } else {
          this.statements(effectiveSlotStatements(model, effFirst), { slot: effFirst, path: '' });
        }
      }
      return;
    }

    // Normal split or second is home here
    this.out.line(`${split.branch} ${label(split.secondLabel)}`);
    if (firstHasCode) {
      if (firstSharedLabel) {
        if (firstIsHome) {
          this.out.label(firstSharedLabel);
          this.statements(effectiveSlotStatements(model, effFirst), { slot: effFirst, path: '' });
        } else {
          this.out.line(`BRA ${firstSharedLabel}`);
        }
      } else {
        this.statements(effectiveSlotStatements(model, effFirst), { slot: effFirst, path: '' });
      }
    }
    this.out.line('RTL');
    this.out.label(label(split.secondLabel));
    if (secondHasCode) {
      if (secondSharedLabel && secondIsHome) {
        this.out.label(secondSharedLabel);
      }
      this.statements(effectiveSlotStatements(model, effSecond), { slot: effSecond, path: '' });
    }
  }

  statements(statements: Statement[], parent: LineOrigin): void {
    statements.forEach((statement, i) => this.statement(statement, at(parent, i)));
  }

  private statement(statement: Statement, origin: LineOrigin): void {
    if (statement.type === 'action') {
      const saves = this.savesFor(statement.piece, origin);
      this.push(saves, origin);
      this.out.pieceCode(this.renderPiece(statement.piece, 'action', origin), origin);
      this.pull(saves, origin);
      return;
    }
    if (statement.type === 'atNeighbour') {
      const { direction, distance, body } = statement;
      const hexDist = distance.toString(16).toUpperCase().padStart(4, '0');
      this.out.line('REP #$20', origin);
      this.out.line('LDA $98', origin);
      this.out.line('PHA', origin);
      this.out.line('LDA $9A', origin);
      this.out.line('PHA', origin);
      if (direction === 'above') {
        this.out.line('LDA $98', origin);
        this.out.line('SEC', origin);
        this.out.line(`SBC #$${hexDist}`, origin);
        this.out.line('STA $98', origin);
      } else if (direction === 'below') {
        this.out.line('LDA $98', origin);
        this.out.line('CLC', origin);
        this.out.line(`ADC #$${hexDist}`, origin);
        this.out.line('STA $98', origin);
      } else if (direction === 'left') {
        this.out.line('LDA $9A', origin);
        this.out.line('SEC', origin);
        this.out.line(`SBC #$${hexDist}`, origin);
        this.out.line('STA $9A', origin);
      } else if (direction === 'right') {
        this.out.line('LDA $9A', origin);
        this.out.line('CLC', origin);
        this.out.line(`ADC #$${hexDist}`, origin);
        this.out.line('STA $9A', origin);
      }
      this.out.line('SEP #$20', origin);
      this.statements(body, at(origin, 'body'));
      this.out.line('REP #$20', origin);
      this.out.line('PLA', origin);
      this.out.line('STA $9A', origin);
      this.out.line('PLA', origin);
      this.out.line('STA $98', origin);
      this.out.line('SEP #$20', origin);
      return;
    }
    const label = this.labels.instance();
    const { branches } = statement;
    branches.forEach((branch, i) => {
      const last = i === branches.length - 1;
      const falseTarget = !last ? `branch${i + 2}` : statement.else ? 'else' : 'end';
      const branchOrigin = at(origin, 'branches', i);
      if (i > 0) this.out.label(label(`branch${i + 1}`), origin);
      this.condition(branch.condition, at(branchOrigin, 'condition'), label(falseTarget));
      this.statements(branch.body, at(branchOrigin, 'body'));
      if (!last || statement.else) this.out.line(`BRA ${label('end')}`, origin);
    });
    if (statement.else) {
      this.out.label(label('else'), origin);
      this.statements(statement.else, at(origin, 'else'));
    }
    this.out.label(label('end'), origin);
  }

  /**
   * Code that falls through when `expr` holds and jumps to `falseLabel` when it does not; the
   * same contract as a single Condition Piece, so combinations nest freely.
   */
  private condition(expr: ConditionExpr, origin: LineOrigin, falseLabel: string): void {
    switch (expr.type) {
      case 'condition':
        return this.conditionPiece(expr.piece, origin, falseLabel);
      case 'and':
        this.condition(expr.left, at(origin, 'left'), falseLabel);
        this.condition(expr.right, at(origin, 'right'), falseLabel);
        return;
      case 'or': {
        // Left false: try right. Left true: skip right.
        const label = this.labels.instance();
        this.condition(expr.left, at(origin, 'left'), label('right'));
        this.out.line(`BRA ${label('true')}`, origin);
        this.out.label(label('right'), origin);
        this.condition(expr.right, at(origin, 'right'), falseLabel);
        this.out.label(label('true'), origin);
        return;
      }
      case 'not': {
        // Inner false: NOT holds, go on. Inner true: NOT fails.
        const label = this.labels.instance();
        this.condition(expr.condition, at(origin, 'condition'), label('pass'));
        this.out.line(`BRA ${falseLabel}`, origin);
        this.out.label(label('pass'), origin);
        return;
      }
    }
  }

  /**
   * A Condition Piece. When it destroys registers that must survive, both ways out restore
   * them: the true path falls through, the false path goes through its own restore.
   */
  private conditionPiece(ref: PieceRef, origin: LineOrigin, falseLabel: string): void {
    const saves = this.savesFor(ref, origin);
    if (saves.length === 0) {
      this.out.pieceCode(this.renderPiece(ref, 'condition', origin, falseLabel), origin);
      return;
    }
    const label = this.labels.instance();
    this.push(saves, origin);
    this.out.pieceCode(this.renderPiece(ref, 'condition', origin, label('restore')), origin);
    this.pull(saves, origin);
    this.out.line(`BRA ${label('pass')}`, origin);
    this.out.label(label('restore'), origin);
    this.pull(saves, origin);
    this.out.line(`BRA ${falseLabel}`, origin);
    this.out.label(label('pass'), origin);
  }

  /**
   * Registers to keep around a Piece (spec "Generator rules"): Y always, as it is the act-as
   * high byte; X in Sprite and Fireball Slots, where it is the sprite index. A is scratch.
   */
  private savesFor(ref: PieceRef, origin: LineOrigin): SavedRegister[] {
    const clobbers = this.library.pieces.get(ref.id)?.manifest.clobbers ?? [];
    const xMatters = slotKind(origin.slot) === 'sprite' || origin.slot === 'marioFireball';
    return (['X', 'Y'] as const).filter(
      (register) => clobbers.includes(register) && (register === 'Y' || xMatters),
    );
  }

  private push(registers: SavedRegister[], origin: LineOrigin): void {
    for (const register of registers) this.out.line(`PH${register}`, origin);
  }

  /** Pulls in reverse order of `push`. */
  private pull(registers: SavedRegister[], origin: LineOrigin): void {
    for (const register of [...registers].reverse()) this.out.line(`PL${register}`, origin);
  }

  /** The Piece's code with its parameter values filled in. */
  private renderPiece(
    ref: PieceRef,
    kind: Manifest['kind'],
    origin: LineOrigin,
    falseLabel?: string,
  ): string {
    const piece = this.library.pieces.get(ref.id);
    if (!piece) throw new GenerateError(`Piece '${ref.id}' is not in the Library`, origin);
    if (piece.manifest.kind !== kind) {
      throw new GenerateError(
        `Piece '${ref.id}' is ${ARTICLE[piece.manifest.kind]}, not ${ARTICLE[kind]}`,
        origin,
      );
    }
    const { slots } = piece.manifest;
    if (slots !== 'any' && !fitsSlot(slots, slotKind(origin.slot))) {
      throw new GenerateError(
        `Piece '${ref.id}' only works in ${SLOT_KIND_NAMES[slots]} Slots`,
        origin,
      );
    }
    this.used.set(ref.id, piece);
    const params: Record<string, Value> = {
      ...Object.fromEntries(piece.manifest.params.map((p) => [p.name, p.default])),
      ...ref.params,
    };
    try {
      return render(piece.template, {
        params,
        label: this.labels.instance(),
        slot: origin.slot,
        ...(falseLabel !== undefined && { falseLabel }),
      });
    } catch (error) {
      if (error instanceof TemplateError) {
        throw new GenerateError(`Piece '${ref.id}': ${error.message}`, origin);
      }
      throw error;
    }
  }
}

/** The origin of a child in the statement tree, e.g. `at({…, path: '/0'}, 'branches', 1)`. */
function at(origin: LineOrigin, ...steps: (string | number)[]): LineOrigin {
  return { slot: origin.slot, path: `${origin.path}/${steps.join('/')}` };
}
