// Names of the sound effects each SPC700 port plays, as listed by the SMWCentral RAM map for
// $7E1DF9–$7E1DFC (values of a clean ROM; AddmusicK can remap them). The list of a port is
// [value, name] pairs; special values (`80+`, `35+`, `FF`) are left out.

export const SOUND_NAMES: Readonly<Record<string, readonly (readonly [number, string])[]>> = {
  $1DF9: [
    [0x00, 'Nothing'],
    [0x01, 'Hit head'],
    [0x02, 'Contact (spin jump on a spiky enemy)'],
    [0x03, 'Kick shell'],
    [0x04, 'Go in pipe / Get hurt'],
    [0x05, 'Midway point'],
    [0x06, 'Yoshi gulp'],
    [0x07, 'Dry bones collapse'],
    [0x08, 'Kill enemy with a spin jump'],
    [0x09, 'Fly with cape'],
    [0x0a, 'Get powerup'],
    [0x0b, 'ON/OFF switch'],
    [0x0c, 'Carry item past the goal'],
    [0x0d, 'Get cape'],
    [0x0e, 'Swim'],
    [0x0f, 'Hurt while flying / Net panel rotates'],
    [0x10, 'Magikoopa shoot magic'],
    [0x11, 'Pause (stops music)'],
    [0x12, 'Unpause (resumes music)'],
    [0x13, 'Enemy stomp 1'],
    [0x14, 'Enemy stomp 2'],
    [0x15, 'Enemy stomp 3'],
    [0x16, 'Enemy stomp 4'],
    [0x17, 'Enemy stomp 5'],
    [0x18, 'Enemy stomp 6'],
    [0x19, 'Enemy stomp 7'],
    [0x1a, 'Grinder (slightly louder than the one in $1DFA)'],
    [0x1b, 'Grinder (slightly louder than the one in $1DFA)'],
    [0x1c, 'Dragon/Yoshi coin'],
    [0x1d, 'Running out of time (combine with the one in $1DFC, does not speed up tempo)'],
    [0x1e, 'P-Balloon'],
    [0x1f, 'Koopaling shrinking/defeated'],
    [0x20, 'Yoshi spit ("OW!")'],
    [0x21, 'Valley of Bowser appears (a low, looping, rumbling noise)'],
    [0x22, 'Silence'],
    [0x23, 'Lemmy/Wendy fall'],
    [0x24, 'Silence'],
    [0x25, 'Blargg roar'],
    [0x26, 'Firework whistle 1'],
    [0x27, 'Firework bang 1'],
    [0x28, 'Firework whistle 2 (louder than #1)'],
    [0x29, 'Firework bang 2 (louder than #1)'],
    [0x2a, 'Peach pops up from the Clown car'],
  ],
  $1DFA: [
    [0x00, 'Nothing'],
    [0x01, 'Jump'],
    [0x02, 'Turn on Yoshi Drum channel (channel #5)'],
    [0x03, 'Turn off Yoshi Drum channel (channel #5)'],
    [0x04, 'Grinder'],
  ],
  $1DFC: [
    [0x00, 'Nothing'],
    [0x01, 'Coin'],
    [0x02, 'Hit a ? block'],
    [0x03, 'Hit a ? block with a vine inside'],
    [0x04, 'Spin jump'],
    [0x05, '1-Up'],
    [0x06, 'Shoot fireball'],
    [0x07, 'Shatter block / Monty Mole popping from the ground'],
    [0x08, 'Springboard'],
    [0x09, 'Bullet Bill shot / Bob-Omb explosion / Thwomp landing'],
    [0x0a, 'Egg hatch'],
    [0x0b, 'Item placed in reserve box'],
    [0x0c, 'Item falls from the reserve box'],
    [0x0d, 'Same as 0C'],
    [0x0e, 'L/R screen scroll'],
    [0x0f, 'Door'],
    [0x10, 'Same as 09'],
    [0x11, 'Drumroll start (looped)'],
    [0x12, 'Drumroll end'],
    [0x13, 'Lose Yoshi'],
    [0x14, 'Unused (Used in SMW2:YI as the sound of a new level becoming available)'],
    [0x15, 'Overworld tile revealed'],
    [0x16, 'Overworld castle collapsed'],
    [0x17, 'Fire spit (used by Yoshi and Bowser Statues)'],
    [0x18, 'Thunder'],
    [0x19, "Clappin' Chuck clap / Bubble pop"],
    [0x1a, 'Castle destruction bomb'],
    [0x1b, 'Castle destruction bomb fuse'],
    [0x1c, 'Overworld Switch Palace block ejection'],
    [0x1d, 'Running out of time (combine with the one in $1DF9, does not speed up tempo)'],
    [0x1e, "Whistlin' Chuck whistle"],
    [0x1f, 'Mounting Yoshi'],
    [0x20, 'Lemmy/Wendy lands in the lava'],
    [0x21, "Yoshi's tongue"],
    [0x22, 'Message box / Save prompt'],
    [0x23, 'Mario moves onto a level tile'],
    [0x24, 'P-Switch time running out'],
    [0x25, 'Yoshi stomps an enemy'],
    [0x26, 'Swooper'],
    [0x27, 'Podoboo'],
    [0x28, 'Enemy stunned/hurt (like Chucks or Koopalings)'],
    [0x29, 'Correct'],
    [0x2a, 'Wrong'],
    [0x2b, 'Firework whistle'],
    [0x2c, 'Firework bang'],
    [0x2d, 'Podoboo (-100% pan)'],
    [0x2e, 'Podoboo (-71% pan)'],
    [0x2f, 'Podoboo (-43% pan)'],
    [0x30, 'Podoboo (-14% pan)'],
    [0x31, 'Podoboo (14% pan)'],
    [0x32, 'Podoboo (43% pan)'],
    [0x33, 'Podoboo (71% pan)'],
    [0x34, 'Podoboo (100% pan)'],
  ],
};
