;@bc-format 1
;@bc-model {"properties":{"author":"BlockCreator","defaultActAs":304,"description":"A body too long for a short branch.","name":"long_body"},"slots":{"marioTop":[{"branches":[{"body":[{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"},{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"}],"condition":{"piece":{"id":"c_onoff","params":{"position":0},"version":1},"type":"condition"}}],"else":[{"piece":{"id":"act_as","params":{"tile":37},"version":1},"type":"action"}],"type":"if"}]}}
;@bc-checksum b8008d06
;
; long_body
; Generated by BlockCreator test. Edit this Block in BlockCreator; hand edits are overwritten.
; Author: BlockCreator
; Insert with act as 130.
;
; A body too long for a short branch.
;

db $42
JMP MarioBelow : JMP MarioAbove : JMP MarioSide
JMP SpriteV : JMP SpriteH : JMP MarioCape : JMP MarioFireball
JMP TopCorner : JMP BodyInside : JMP HeadInside

MarioAbove:
TopCorner:
	LDA $14AF|!addr
	BEQ bc24_skip
	JMP bc1_else
bc24_skip:
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	LDY #$01
	LDA #$30
	STA $1693|!addr
	BRA bc1_end
bc1_else:
	LDY #$00
	LDA #$25
	STA $1693|!addr
bc1_end:
	RTL

MarioBelow:
MarioSide:
SpriteV:
SpriteH:
MarioCape:
MarioFireball:
BodyInside:
HeadInside:
	RTL

print "A body too long for a short branch."
