;bc-format 1
;bc-model {"properties":{"author":"BlockCreator","defaultActAs":304,"description":"Nested if with else-if.","name":"nested_if"},"slots":{"marioTop":[{"branches":[{"body":[{"branches":[{"body":[{"piece":{"id":"act_as","params":{"tile":303},"version":1},"type":"action"}],"condition":{"piece":{"id":"c_onoff","params":{"position":1},"version":1},"type":"condition"}},{"body":[{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"}],"condition":{"piece":{"id":"c_onoff","params":{"position":0},"version":1},"type":"condition"}}],"type":"if"}],"condition":{"piece":{"id":"c_onoff","params":{"position":0},"version":1},"type":"condition"}}],"else":[{"piece":{"id":"act_as","params":{"tile":37},"version":1},"type":"action"}],"type":"if"}]}}
;bc-checksum 89571b7f
;
; nested_if
; Generated by BlockCreator test. Edit this Block in BlockCreator; hand edits are overwritten.
; Author: BlockCreator
; Insert with act as 130.
;
; Nested if with else-if.
;

db $42
JMP MarioBelow : JMP MarioAbove : JMP MarioSide
JMP SpriteV : JMP SpriteH : JMP MarioCape : JMP MarioFireball
JMP TopCorner : JMP BodyInside : JMP HeadInside

MarioAbove:
TopCorner:
	LDA $14AF|!addr
	BNE bc1_else
	LDA $14AF|!addr
	BEQ bc3_branch2
	LDY #$01
	LDA #$2F
	STA $1693|!addr
	BRA bc3_end
bc3_branch2:
	LDA $14AF|!addr
	BNE bc3_end
	LDY #$01
	LDA #$30
	STA $1693|!addr
bc3_end:
	BRA bc1_end
bc1_else:
	LDY #$00
	LDA #$25
	STA $1693|!addr
bc1_end:
	RTL

MarioBelow:
MarioSide:
SpriteV:
SpriteH:
MarioCape:
MarioFireball:
BodyInside:
HeadInside:
	RTL

print "Nested if with else-if."
