;@bc-format 1
;@bc-model {"properties":{"author":"BlockCreator","defaultActAs":304,"description":"Mario can stand on it only while the switch is ON.","name":"onoff_cement"},"slots":{"marioTop":[{"branches":[{"body":[{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"}],"condition":{"piece":{"id":"c_onoff","params":{"position":0},"version":1},"type":"condition"}}],"else":[{"piece":{"id":"act_as","params":{"tile":37},"version":1},"type":"action"}],"type":"if"}]}}
;@bc-checksum 877ed9e1
;
; onoff_cement
; Generated by BlockCreator test. Edit this Block in BlockCreator; hand edits are overwritten.
; Author: BlockCreator
; Insert with act as 130.
;
; Mario can stand on it only while the switch is ON.
;

db $42
JMP MarioBelow : JMP MarioAbove : JMP MarioSide
JMP SpriteV : JMP SpriteH : JMP MarioCape : JMP MarioFireball
JMP TopCorner : JMP BodyInside : JMP HeadInside

MarioAbove:
	LDA $14AF|!addr
	BNE bc1_else
	LDY #$01
	LDA #$30
	STA $1693|!addr
	BRA bc1_end
bc1_else:
	LDY #$00
	LDA #$25
	STA $1693|!addr
bc1_end:
	RTL

MarioBelow:
MarioSide:
SpriteV:
SpriteH:
MarioCape:
MarioFireball:
TopCorner:
BodyInside:
HeadInside:
	RTL

print "Mario can stand on it only while the switch is ON."
