;@bc-format 1
;@bc-model {"properties":{"author":"BlockCreator","defaultActAs":304,"description":"Solid while the switch is ON or OFF.","name":"or_switch"},"slots":{"marioTop":[{"branches":[{"body":[{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"}],"condition":{"left":{"piece":{"id":"c_onoff","params":{"position":0},"version":1},"type":"condition"},"right":{"piece":{"id":"c_onoff","params":{"position":1},"version":1},"type":"condition"},"type":"or"}}],"type":"if"}]}}
;@bc-checksum 1e30b06e
;
; or_switch
; Generated by BlockCreator test. Edit this Block in BlockCreator; hand edits are overwritten.
; Author: BlockCreator
; Insert with act as 130.
;
; Solid while the switch is ON or OFF.
;

db $42
JMP MarioBelow : JMP MarioAbove : JMP MarioSide
JMP SpriteV : JMP SpriteH : JMP MarioCape : JMP MarioFireball
JMP TopCorner : JMP BodyInside : JMP HeadInside

MarioAbove:
TopCorner:
	LDA $14AF|!addr
	BNE bc2_right
	BRA bc2_true
bc2_right:
	LDA $14AF|!addr
	BEQ bc1_end
bc2_true:
	LDY #$01
	LDA #$30
	STA $1693|!addr
bc1_end:
	RTL

MarioBelow:
MarioSide:
SpriteV:
SpriteH:
MarioCape:
MarioFireball:
BodyInside:
HeadInside:
	RTL

print "Solid while the switch is ON or OFF."
