;@bc-format 1
;@bc-model {"properties":{"author":"BlockCreator","defaultActAs":304,"description":"Solid from the left, air from the right.","name":"side_split"},"slots":{"marioLeft":[{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"}],"marioRight":[{"piece":{"id":"act_as","params":{"tile":37},"version":1},"type":"action"}]}}
;@bc-checksum c73619c0
;
; side_split
; Generated by BlockCreator test. Edit this Block in BlockCreator; hand edits are overwritten.
; Author: BlockCreator
; Insert with act as 130.
;
; Solid from the left, air from the right.
;

db $42
JMP MarioBelow : JMP MarioAbove : JMP MarioSide
JMP SpriteV : JMP SpriteH : JMP MarioCape : JMP MarioFireball
JMP TopCorner : JMP BodyInside : JMP HeadInside

MarioSide:
	LDA $93 ; 0: Mario is left of the block
	BNE bc1_right
	LDY #$01
	LDA #$30
	STA $1693|!addr
	RTL
bc1_right:
	LDY #$00
	LDA #$25
	STA $1693|!addr
	RTL

MarioBelow:
MarioAbove:
SpriteV:
SpriteH:
MarioCape:
MarioFireball:
TopCorner:
BodyInside:
HeadInside:
	RTL

print "Solid from the left, air from the right."
