;bc-format 1
;bc-model {"properties":{"author":"BlockCreator","defaultActAs":37,"description":"Sprites stand on it; from the left it is solid while ON.","name":"sprite_platform"},"slots":{"spriteLeft":[{"branches":[{"body":[{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"}],"condition":{"piece":{"id":"c_onoff","params":{"position":0},"version":1},"type":"condition"}}],"type":"if"}],"spriteTop":[{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"}]}}
;bc-checksum f6bd6496
;
; sprite_platform
; Generated by BlockCreator test. Edit this Block in BlockCreator; hand edits are overwritten.
; Author: BlockCreator
; Insert with act as 025.
;
; Sprites stand on it; from the left it is solid while ON.
;

db $42
JMP MarioBelow : JMP MarioAbove : JMP MarioSide
JMP SpriteV : JMP SpriteH : JMP MarioCape : JMP MarioFireball
JMP TopCorner : JMP BodyInside : JMP HeadInside

SpriteV:
	%sprite_block_position()
	LDA !AA,x ; negative: moving up, touches the bottom
	BMI bc1_bottom
	LDY #$01
	LDA #$30
	STA $1693|!addr
	RTL
bc1_bottom:
	RTL

SpriteH:
	%sprite_block_position()
	LDA !B6,x ; negative: moving left, touches the right side
	BMI bc3_right
	LDA $14AF|!addr
	BNE bc4_end
	LDY #$01
	LDA #$30
	STA $1693|!addr
bc4_end:
	RTL
bc3_right:
	RTL

MarioBelow:
MarioAbove:
MarioSide:
MarioCape:
MarioFireball:
TopCorner:
BodyInside:
HeadInside:
	RTL

print "Sprites stand on it; from the left it is solid while ON."
