;@bc-format 1
;@bc-model {"properties":{"author":"BlockCreator","defaultActAs":304,"description":"Solid on top; wall-running Mario passes through.","name":"wall_run"},"slots":{"marioTop":[{"piece":{"id":"act_as","params":{"tile":304},"version":1},"type":"action"}],"marioWallBody":[{"piece":{"id":"act_as","params":{"tile":37},"version":1},"type":"action"}],"marioWallFeet":[{"piece":{"id":"act_as","params":{"tile":37},"version":1},"type":"action"}]}}
;@bc-checksum 2b081e47
;
; wall_run
; Generated by BlockCreator test. Edit this Block in BlockCreator; hand edits are overwritten.
; Author: BlockCreator
; Insert with act as 130.
;
; Solid on top; wall-running Mario passes through.
;

db $37
JMP MarioBelow : JMP MarioAbove : JMP MarioSide
JMP SpriteV : JMP SpriteH : JMP MarioCape : JMP MarioFireball
JMP TopCorner : JMP BodyInside : JMP HeadInside
JMP WallFeet : JMP WallBody

MarioAbove:
TopCorner:
	LDY #$01
	LDA #$30
	STA $1693|!addr
	RTL

WallFeet:
	LDY #$00
	LDA #$25
	STA $1693|!addr
	RTL

WallBody:
	LDY #$00
	LDA #$25
	STA $1693|!addr
	RTL

MarioBelow:
MarioSide:
SpriteV:
SpriteH:
MarioCape:
MarioFireball:
BodyInside:
HeadInside:
	RTL

print "Solid on top; wall-running Mario passes through."
